### ISSUE TITLE
Plasma windows

### ISSUE THREAD

**Issue by albfla96** [ScotchBoard/Pathfinder-Genesis#5]
We should circumscribe the levels between glass walls, cuz of the awesome milky way skybox.
Dem walls should be similar to the plasma glass windows from the space shuttles.

**Comment by ChiuRobert** [comment]
What he means is something like this: http://ak4.picdn.net/shutterstock/videos/8903854/thumb/2.jpg
That kind of spaceship gate from which little fighters can leave or get back in, the door that protects the crew from well.. space and can be seen through. Its color is usually light blue or something close to that. Basically, it's like a piece of light blue glass with stronger color on the edges.
